[package]
name = "rustegram"
version = "0.1.0"
authors = ["Marco Napetti <marco.napetti@pixartprinting.com>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11.2"
regex = "0.2"
lazy_static = "1.0.0"
serde_json = "1.0"
rust-ini = "0.9"
