[package]
name = "client_lib"
version = "0.1.0"
authors = ["Marco Napetti <marco.napetti@pixartprinting.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
url = "1.0"
rust-ini = "0.9"
