[package]
name = "client_lib"
version = "0.1.0"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]

[dependencies]
reqwest = "0.9"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4"
parking_lot = "0.6"
