[package]
name = "no_fly_bot"
version = "0.1.0"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]

[lib]
name = "no_fly_bot"
crate-type = ["dylib"]

[dependencies]
client_lib = { path = "../../client_lib" }
toml = "0.4"
serde_json = "1.0"
